"use client";

import { useEffect, useMemo, useState } from 'react';
import { AlertCircle, Check, Edit2, Loader2, Plus, Search, Tag, Trash2, X } from 'lucide-react';
import apiClient from '@/lib/apiClient';
import styles from './offers.module.css';

type Status = 'DRAFT' | 'ACTIVE' | 'PAUSED' | 'EXPIRED';
type ApplyTo = 'ALL' | 'SELECTED';
type DiscountType = 'PERCENTAGE' | 'FIXED';

interface Product { id:string; title:string; price:number; thumbnail?:string|null; category?:string; }
interface Offer { id:string; name:string; type:DiscountType; value:number; applyTo:ApplyTo; minOrderAmount:number|null; couponCode:string|null; autoApply:boolean; status:Status; startAt:string; endAt:string; products?:Array<{id:string;title:string}>; }
interface FormState { name:string; type:DiscountType; value:string; applyTo:ApplyTo; productIds:string[]; minOrderAmount:string; couponCode:string; autoApply:boolean; status:Status; startAt:string; endAt:string; }

const blankForm=():FormState=>({name:'',type:'PERCENTAGE',value:'',applyTo:'ALL',productIds:[],minOrderAmount:'',couponCode:'',autoApply:true,status:'ACTIVE',startAt:'',endAt:''});
const toInputDate=(value?:string)=>{if(!value)return ''; const date=new Date(value); if(Number.isNaN(date.getTime()))return ''; const local=new Date(date.getTime()-date.getTimezoneOffset()*60000); return local.toISOString().slice(0,16);};
const toIso=(value:string)=>new Date(value).toISOString();

export default function OffersPage(){
    const [offers,setOffers]=useState<Offer[]>([]); const [products,setProducts]=useState<Product[]>([]);
    const [loading,setLoading]=useState(true); const [loadError,setLoadError]=useState<string|null>(null);
    const [modalOpen,setModalOpen]=useState(false); const [editingId,setEditingId]=useState<string|null>(null); const [saving,setSaving]=useState(false); const [deletingId,setDeletingId]=useState<string|null>(null); const [formError,setFormError]=useState('');
    const [search,setSearch]=useState(''); const [form,setForm]=useState<FormState>(blankForm());

    const loadData=async()=>{setLoading(true);setLoadError(null);try{const [offerRes,productRes]=await Promise.all([apiClient.get('/offers/admin'),apiClient.get('/admin/products?limit=100')]); setOffers(Array.isArray(offerRes.data)?offerRes.data:[]); const productRows=Array.isArray(productRes.data?.data)?productRes.data.data:[]; setProducts(productRows);}catch(err){console.error(err);setLoadError('Unable to load promotions or products.');}finally{setLoading(false);}};
    useEffect(()=>{loadData();},[]);

    const visibleProducts=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return products;return products.filter(p=>p.title.toLowerCase().includes(q)||(p.category||'').toLowerCase().includes(q));},[products,search]);
    const selectedProducts=useMemo(()=>products.filter(p=>form.productIds.includes(p.id)),[products,form.productIds]);

    const reset=()=>{setModalOpen(false);setEditingId(null);setSaving(false);setFormError('');setSearch('');setForm(blankForm());};
    const openCreate=()=>{setEditingId(null);setForm(blankForm());setFormError('');setSearch('');setModalOpen(true);};
    const openEdit=(offer:Offer)=>{setEditingId(offer.id);setForm({name:offer.name||'',type:offer.type,value:String(offer.value),applyTo:offer.applyTo,productIds:Array.isArray(offer.products)?offer.products.map(p=>p.id):[],minOrderAmount:offer.minOrderAmount==null?'':String(offer.minOrderAmount),couponCode:offer.couponCode||'',autoApply:Boolean(offer.autoApply),status:offer.status,startAt:toInputDate(offer.startAt),endAt:toInputDate(offer.endAt)});setFormError('');setSearch('');setModalOpen(true);};

    const submit=async(e:React.FormEvent)=>{e.preventDefault();setFormError('');const value=Number(form.value);if(!form.name.trim())return setFormError('Offer name is required.');if(!Number.isFinite(value)||value<=0)return setFormError('Enter a valid discount value.');if(form.type==='PERCENTAGE'&&value>100)return setFormError('Percentage discount cannot exceed 100%.');if(form.applyTo==='SELECTED'&&!form.productIds.length)return setFormError('Select at least one product.');if(!form.startAt||!form.endAt)return setFormError('Start and end dates are required.');const start=new Date(form.startAt),end=new Date(form.endAt);if(end<=start)return setFormError('End date must be after the start date.');setSaving(true);try{const payload={name:form.name.trim(),type:form.type,value,applyTo:form.applyTo,productIds:form.applyTo==='SELECTED'?form.productIds:[],minOrderAmount:form.minOrderAmount===''?null:Number(form.minOrderAmount),couponCode:form.couponCode.trim()||null,autoApply:form.autoApply,status:form.status,startAt:toIso(form.startAt),endAt:toIso(form.endAt)};if(editingId)await apiClient.put(`/offers/admin/${editingId}`,payload);else await apiClient.post('/offers/admin',payload);await loadData();reset();}catch(err:any){setFormError(err?.response?.data?.error||'Failed to save offer.');}finally{setSaving(false);}};

    const remove=async(id:string)=>{if(deletingId)return;setDeletingId(id);try{await apiClient.delete(`/offers/admin/${id}`);setOffers(prev=>prev.filter(o=>o.id!==id));}catch(err:any){setLoadError(err?.response?.data?.error||'Failed to delete offer.');}finally{setDeletingId(null);}};

    return <main className={styles.page}><div className={styles.pageInner}>
        <header className={styles.header}><div><p className={styles.eyebrow}>PLUTEN / PROMOTIONS</p><h1>Offers</h1><p className={styles.subtitle}>Create precise, product-level discounts without touching checkout code.</p></div><button className={styles.primaryButton} onClick={openCreate}><Plus size={18}/>Create offer</button></header>
        {loading?<div className={styles.loading}><Loader2 className={styles.spin} size={30}/><span>Loading promotions</span></div>:loadError?<div className={styles.errorState}><AlertCircle size={22}/><h2>Promotions unavailable.</h2><p>{loadError}</p><button className={styles.secondaryButton} onClick={loadData}>Retry</button></div>:<>
            <div className={styles.summary}><span><strong>{offers.length}</strong> total offers</span><span><strong>{offers.filter(o=>o.status==='ACTIVE').length}</strong> active</span></div>
            {offers.length===0?<div className={styles.empty}><Tag size={22}/><h2>No offers yet.</h2><p>Create your first promotion for all products or a precise product selection.</p><button className={styles.primaryButton} onClick={openCreate}><Plus size={17}/>Create offer</button></div>:<div className={styles.tableCard}><div className={styles.tableScroll}><table><thead><tr><th>Offer</th><th>Discount</th><th>Applies to</th><th>Status</th><th>Valid until</th><th>Actions</th></tr></thead><tbody>{offers.map(offer=><tr key={offer.id}><td><strong>{offer.name}</strong>{offer.autoApply&&<span className={styles.autoPill}>Auto</span>}</td><td>{offer.type==='PERCENTAGE'?`${offer.value}% OFF`:`₹${Number(offer.value).toLocaleString('en-IN')} OFF`}</td><td>{offer.applyTo==='ALL'?'All products':`${Array.isArray(offer.products)?offer.products.length:0} selected`}</td><td><span className={`${styles.status} ${styles[offer.status.toLowerCase()]}`}>{offer.status}</span></td><td>{new Date(offer.endAt).toLocaleString('en-IN',{day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit'})}</td><td><div className={styles.rowActions}><button className={styles.iconButton} onClick={()=>openEdit(offer)} aria-label={`Edit ${offer.name}`}><Edit2 size={16}/></button><button className={`${styles.iconButton} ${styles.danger}`} onClick={()=>remove(offer.id)} disabled={deletingId===offer.id} aria-label={`Delete ${offer.name}`}>{deletingId===offer.id?<Loader2 className={styles.spin} size={16}/>:<Trash2 size={16}/>}</button></div></td></tr>)}</tbody></table></div></div>}
        </>}
    </div>

    {modalOpen&&<div className={styles.overlay} role="dialog" aria-modal="true" aria-labelledby="offer-editor-title"><div className={styles.modal}><div className={styles.modalHeader}><div><p className={styles.eyebrow}>PLUTEN / OFFER ENGINE</p><h2 id="offer-editor-title">{editingId?'Edit offer':'Create offer'}</h2></div><button className={styles.closeButton} onClick={reset} aria-label="Close offer editor"><X size={19}/></button></div>
        {formError&&<div className={styles.formError}><AlertCircle size={16}/>{formError}</div>}
        <form className={styles.form} onSubmit={submit}>
            <div className={styles.field}><label>Offer name</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Launch week" autoFocus/></div>
            <div className={styles.twoCol}><div className={styles.field}><label>Discount type</label><select value={form.type} onChange={e=>setForm({...form,type:e.target.value as DiscountType})}><option value="PERCENTAGE">Percentage</option><option value="FIXED">Fixed amount</option></select></div><div className={styles.field}><label>{form.type==='PERCENTAGE'?'Discount %':'Discount amount'}</label><input inputMode="decimal" value={form.value} onChange={e=>setForm({...form,value:e.target.value})} placeholder="20"/></div></div>
            <div className={styles.field}><label>Applies to</label><div className={styles.segmented}><button type="button" className={form.applyTo==='ALL'?styles.segmentActive:styles.segment} onClick={()=>setForm({...form,applyTo:'ALL',productIds:[]})}>All products</button><button type="button" className={form.applyTo==='SELECTED'?styles.segmentActive:styles.segment} onClick={()=>setForm({...form,applyTo:'SELECTED'})}>Selected products</button></div></div>
            {form.applyTo==='SELECTED'&&<div className={styles.productPicker}><div className={styles.searchBox}><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products..."/></div><div className={styles.selectionHeader}><span><strong>{form.productIds.length}</strong> selected</span><button type="button" onClick={()=>setForm({...form,productIds:[]})} disabled={!form.productIds.length}>Clear</button></div><div className={styles.productList}>{visibleProducts.length===0?<p className={styles.noResults}>No products found.</p>:visibleProducts.map(product=>{const checked=form.productIds.includes(product.id);return <button type="button" key={product.id} className={checked?styles.productOptionActive:styles.productOption} onClick={()=>setForm({...form,productIds:checked?form.productIds.filter(id=>id!==product.id):[...form.productIds,product.id]})}><span className={styles.checkbox}>{checked?<Check size={14}/>:null}</span><span className={styles.productOptionText}><strong>{product.title}</strong><small>₹{Number(product.price).toLocaleString('en-IN')}</small></span></button>})}</div>{selectedProducts.length>0&&<div className={styles.selectedSummary}>{selectedProducts.map(p=><span key={p.id}>{p.title}<button type="button" onClick={()=>setForm({...form,productIds:form.productIds.filter(id=>id!==p.id)})} aria-label={`Remove ${p.title}`}><X size={12}/></button></span>)}</div>}</div>}
            <div className={styles.twoCol}><div className={styles.field}><label>Minimum order</label><input inputMode="decimal" value={form.minOrderAmount} onChange={e=>setForm({...form,minOrderAmount:e.target.value})} placeholder="Optional"/></div><div className={styles.field}><label>Coupon code</label><input value={form.couponCode} onChange={e=>setForm({...form,couponCode:e.target.value})} placeholder="Optional"/></div></div>
            <div className={styles.twoCol}><div className={styles.field}><label>Start</label><input type="datetime-local" value={form.startAt} onChange={e=>setForm({...form,startAt:e.target.value})}/></div><div className={styles.field}><label>End</label><input type="datetime-local" value={form.endAt} onChange={e=>setForm({...form,endAt:e.target.value})}/></div></div>
            <div className={styles.switchRow}><div><strong>Auto apply</strong><span>Use automatically when this offer is eligible.</span></div><button type="button" aria-pressed={form.autoApply} className={form.autoApply?styles.switchOn:styles.switchOff} onClick={()=>setForm({...form,autoApply:!form.autoApply})}><span/></button></div>
            <div className={styles.field}><label>Status</label><select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Status})}><option value="DRAFT">Draft</option><option value="ACTIVE">Active</option><option value="PAUSED">Paused</option><option value="EXPIRED">Expired</option></select></div>
            <div className={styles.modalActions}><button type="button" className={styles.secondaryButton} onClick={reset}>Cancel</button><button type="submit" className={styles.primaryButton} disabled={saving}>{saving?<><Loader2 className={styles.spin} size={17}/>Saving</>:editingId?'Save changes':'Create offer'}</button></div>
        </form>
    </div></div>}
    </main>;
}
