"use client";
import { useEffect, useMemo, useState } from 'react';
import { AlertCircle, CheckCircle2, ChevronLeft, ChevronRight, Clock, Loader2, XCircle } from 'lucide-react';
import apiClient from '@/lib/apiClient';
import styles from '../admin.module.css';

type Order={id:string;totalAmount:number;status:string;transactionId:string;createdAt:string;user:{email:string;firstName:string|null;lastName:string|null};product:{title:string}};
const PAGE=10;
export default function AdminOrdersPage(){
 const [rows,setRows]=useState<Order[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(1);
 const load=async()=>{setLoading(true);setError('');try{const res=await apiClient.get('/admin/orders');setRows(Array.isArray(res.data)?res.data:[]);}catch(err:any){setError(err?.response?.data?.error||'Unable to load the financial ledger.');}finally{setLoading(false);}};useEffect(()=>{load();},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?rows.filter(o=>o.transactionId?.toLowerCase().includes(q)||o.user.email.toLowerCase().includes(q)||o.product.title.toLowerCase().includes(q)):rows;},[rows,query]);const pages=Math.max(1,Math.ceil(filtered.length/PAGE));const visible=filtered.slice((page-1)*PAGE,page*PAGE);useEffect(()=>setPage(1),[query]);
 const icon=(s:string)=>s==='SUCCESS'?<CheckCircle2 size={15}/>:s==='PENDING'?<Clock size={15}/>:<XCircle size={15}/>;
 return <main className={styles.dashboardContainer}><div className={styles.header}><div><p className={styles.pageEyebrow}>PLUTEN / PAYMENTS</p><h1 className={styles.pageTitle}>Orders</h1></div><span className={styles.topbarRole}>{filtered.length} records</span></div><div className={styles.pageToolbar}><input className={styles.toolbarSearch} placeholder="Search transaction, email or product..." value={query} onChange={e=>setQuery(e.target.value)}/></div>{loading?<div className={styles.authLoading}><Loader2 size={28} className="pluten-login-spinner"/><span>Loading ledger</span></div>:error?<div className={styles.errorState}><AlertCircle size={22}/><h2>Financial ledger unavailable.</h2><p>{error}</p><button className={styles.primaryButton} onClick={load}>Retry</button></div>:filtered.length===0?<div className={styles.emptyState}><h2>No orders found.</h2><p>Try a different search.</p></div>:<><div className={styles.tableCard}><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th className={styles.th}>Order</th><th className={styles.th}>Customer</th><th className={styles.th}>Product</th><th className={styles.th}>Amount</th><th className={styles.th}>Status</th><th className={styles.th}>Date</th></tr></thead><tbody>{visible.map(o=><tr key={o.id}><td className={styles.td}><span style={{fontFamily:'ui-monospace,monospace',fontSize:10,color:'#85857e'}}>{o.transactionId||o.id.slice(0,12)}</span></td><td className={styles.td}>{o.user.email}</td><td className={styles.td}><strong>{o.product.title}</strong></td><td className={styles.td}>₹{Number(o.totalAmount).toLocaleString('en-IN')}</td><td className={styles.td}><span style={{display:'inline-flex',alignItems:'center',gap:6}}>{icon(o.status)}{o.status}</span></td><td className={styles.td}>{new Date(o.createdAt).toLocaleString('en-IN')}</td></tr>)}</tbody></table></div></div><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,marginTop:16,color:'#777',fontSize:11}}><span>Page {page} of {pages}</span><div style={{display:'flex',gap:6}}><button className={styles.iconBtn} disabled={page===1} onClick={()=>setPage(v=>Math.max(1,v-1))}><ChevronLeft size={16}/></button><button className={styles.iconBtn} disabled={page===pages} onClick={()=>setPage(v=>Math.min(pages,v+1))}><ChevronRight size={16}/></button></div></div></>}</main>;
}
