"use client";

import { useEffect, useMemo, useState } from 'react';
import { AlertCircle, Edit2, Loader2, Plus, Trash2, X } from 'lucide-react';
import apiClient from '@/lib/apiClient';
import styles from './adminProducts.module.css';

interface Product { id:string; title:string; description:string|null; price:number; category:string; thumbnail?:string|null; }
const CATEGORIES=['E-Books','Video Courses','Templates','Software','Consulting','Other'];

export default function AdminProductsPage(){
 const [products,setProducts]=useState<Product[]>([]);
 const [loading,setLoading]=useState(true); const [loadError,setLoadError]=useState('');
 const [query,setQuery]=useState(''); const [modal,setModal]=useState(false); const [editing,setEditing]=useState<string|null>(null);
 const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [deleteId,setDeleteId]=useState<string|null>(null);
 const [title,setTitle]=useState(''); const [category,setCategory]=useState(CATEGORIES[0]); const [description,setDescription]=useState(''); const [price,setPrice]=useState(''); const [thumbnail,setThumbnail]=useState<File|null>(null); const [assetFile,setAssetFile]=useState<File|null>(null);
 const load=async()=>{setLoading(true);setLoadError('');try{const res=await apiClient.get('/admin/products?limit=100');setProducts(Array.isArray(res.data?.data)?res.data.data:[]);}catch(err:any){setLoadError(err?.response?.data?.error||'Unable to load products.');}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase(); return q?products.filter(p=>p.title.toLowerCase().includes(q)||(p.category||'').toLowerCase().includes(q)):products;},[products,query]);
 const reset=()=>{setModal(false);setEditing(null);setSaving(false);setError('');setTitle('');setCategory(CATEGORIES[0]);setDescription('');setPrice('');setThumbnail(null);setAssetFile(null);};
 const openEdit=(p:Product)=>{setEditing(p.id);setTitle(p.title);setCategory(p.category||CATEGORIES[0]);setDescription(p.description||'');setPrice(String(p.price));setError('');setModal(true);};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(!title.trim())return setError('Product title is required.');if(!price||Number(price)<0)return setError('Enter a valid price.');if(!editing&&!assetFile)return setError('Select the digital asset file.');setSaving(true);try{const data=new FormData();data.append('title',title.trim());data.append('description',description.trim());data.append('category',category);data.append('price',price);data.append('isDigital','true');if(thumbnail)data.append('thumbnail',thumbnail);if(assetFile)data.append('assetFile',assetFile);if(editing)await apiClient.put(`/admin/products/${editing}`,data,{headers:{'Content-Type':'multipart/form-data'}});else await apiClient.post('/admin/products',data,{headers:{'Content-Type':'multipart/form-data'}});await load();reset();}catch(err:any){setError(err?.response?.data?.error||'Failed to save product.');}finally{setSaving(false);}};
 const archive=async()=>{if(!deleteId)return;try{await apiClient.delete(`/admin/products/${deleteId}`);setDeleteId(null);await load();}catch(err:any){setLoadError(err?.response?.data?.error||'Failed to archive product.');setDeleteId(null);}};
 return <main className={styles.container}>
  <header className={styles.header}><div><h1 className={styles.title}>Products</h1><p className={styles.sub}>Manage the digital catalog and secure assets.</p></div><button className={styles.primaryButton} onClick={()=>{reset();setModal(true)}}><Plus size={17}/> New product</button></header>
  <div className={styles.toolbar}><input className={styles.search} placeholder="Search products..." value={query} onChange={e=>setQuery(e.target.value)}/><span style={{color:'#777',fontSize:'11px'}}>{filtered.length} products</span></div>
  {loading?<div className={styles.empty}><Loader2 size={28} className="pluten-login-spinner"/><p>Loading catalog</p></div>:loadError?<div className={styles.empty}><AlertCircle size={22}/><h2>Catalog unavailable.</h2><p>{loadError}</p><button className={styles.primaryButton} onClick={load}>Retry</button></div>:filtered.length===0?<div className={styles.empty}><h2>No products found.</h2><p>Create your first digital product or change the search.</p></div>:<div className={styles.tableCard}><div className={styles.tableScroll}><table className={styles.table}><thead><tr><th className={styles.th}>Product</th><th className={styles.th}>Category</th><th className={styles.th}>Price</th><th className={styles.th}>Actions</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td className={styles.td}><div className={styles.productCell}>{p.thumbnail?<img src={p.thumbnail} alt="" className={styles.thumb}/>:<span className={styles.thumbFallback}>PLUTEN</span>}<strong>{p.title}</strong></div></td><td className={styles.td}>{p.category||'Uncategorized'}</td><td className={styles.td}>₹{Number(p.price).toLocaleString('en-IN')}</td><td className={styles.td}><div className={styles.actions}><button className={styles.iconButton} onClick={()=>openEdit(p)} aria-label={`Edit ${p.title}`}><Edit2 size={16}/></button><button className={`${styles.iconButton} ${styles.danger}`} onClick={()=>setDeleteId(p.id)} aria-label={`Archive ${p.title}`}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div></div>}
  {modal&&<div className={styles.modalOverlay} role="dialog" aria-modal="true"><div className={styles.modalContent}><div className={styles.modalHeader}><div><p className={styles.sub}>PLUTEN / CATALOG</p><h2 className={styles.modalTitle}>{editing?'Edit product':'Create product'}</h2></div><button className={styles.closeBtn} onClick={reset} aria-label="Close"><X size={18}/></button></div>{error&&<div className={styles.error}>{error}</div>}<form className={styles.form} onSubmit={submit}><div className={styles.field}><label className={styles.label}>Title</label><input className={styles.input} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Product title"/></div><div className={styles.twoCol}><div className={styles.field}><label className={styles.label}>Category</label><select className={styles.select} value={category} onChange={e=>setCategory(e.target.value)}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></div><div className={styles.field}><label className={styles.label}>Price (INR)</label><input className={styles.input} inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)} placeholder="999"/></div></div><div className={styles.field}><label className={styles.label}>Description</label><textarea className={styles.textarea} value={description} onChange={e=>setDescription(e.target.value)} placeholder="What is inside this product?"/></div><div className={styles.field}><label className={styles.label}>Cover image {editing?'(optional)':'(required)'}</label><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setThumbnail(e.target.files?.[0]||null)}/></div><div className={styles.field}><label className={styles.label}>Digital asset {editing?'(optional)':'(required)'}</label><input type="file" accept=".pdf,.zip,.docx" onChange={e=>setAssetFile(e.target.files?.[0]||null)}/></div><div className={styles.formActions}><button type="button" className={styles.secondaryButton} onClick={reset}>Cancel</button><button type="submit" className={styles.primaryButton} disabled={saving}>{saving?<><Loader2 size={16} className="pluten-login-spinner"/> Saving</>:editing?'Save changes':'Create product'}</button></div></form></div></div>}
  {deleteId&&<div className={styles.modalOverlay} role="dialog" aria-modal="true"><div className={styles.modalContent}><p className={styles.sub}>PLUTEN / PRODUCT</p><h2 className={styles.modalTitle}>Archive this product?</h2><p style={{color:'#888',fontSize:'13px',lineHeight:1.6}}>The product will disappear from the storefront, while existing buyers retain access.</p><div className={styles.formActions}><button className={styles.secondaryButton} onClick={()=>setDeleteId(null)}>Cancel</button><button className={styles.primaryButton} onClick={archive}>Archive product</button></div></div></div>}
 </main>;
}
