"use client";
import { useEffect, useState } from 'react';
import { AlertCircle, Edit2, Loader2, Plus, Trash2, X, ChevronLeft, ChevronRight, Search } from 'lucide-react';
import apiClient from '@/lib/apiClient';
import styles from './adminProducts.module.css';

interface Product { id:string; title:string; description:string|null; price:number; category:string; thumbnail?:string|null; }
interface Pagination { totalRecords:number; currentPage:number; totalPages:number; limit:number; }
const CATEGORIES=['E-Books','Video Courses','Templates','Software','Consulting','Other'];
const PAGE_SIZE=25;

export default function AdminProductsPage(){
  const [products,setProducts]=useState<Product[]>([]);
  const [pagination,setPagination]=useState<Pagination>({totalRecords:0,currentPage:1,totalPages:1,limit:PAGE_SIZE});
  const [loading,setLoading]=useState(true); const [loadError,setLoadError]=useState(''); const [query,setQuery]=useState('');
  const [modal,setModal]=useState(false); const [editing,setEditing]=useState<string|null>(null); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [deleteId,setDeleteId]=useState<string|null>(null);
  const [title,setTitle]=useState(''); const [category,setCategory]=useState(CATEGORIES[0]); const [description,setDescription]=useState(''); const [price,setPrice]=useState(''); const [thumbnail,setThumbnail]=useState<File|null>(null); const [assetFile,setAssetFile]=useState<File|null>(null);

  const load=async(page=1)=>{setLoading(true);setLoadError('');try{const res=await apiClient.get('/admin/products',{params:{page,limit:PAGE_SIZE,search:query.trim()}});setProducts(Array.isArray(res.data?.data)?res.data.data:[]);setPagination(res.data?.pagination||{totalRecords:0,currentPage:page,totalPages:1,limit:PAGE_SIZE});}catch(err:any){setLoadError(err?.response?.data?.error||'Unable to load products.');}finally{setLoading(false);}};
  useEffect(()=>{const timer=setTimeout(()=>load(1),250);return()=>clearTimeout(timer);},[query]);

  const reset=()=>{setModal(false);setEditing(null);setSaving(false);setError('');setTitle('');setCategory(CATEGORIES[0]);setDescription('');setPrice('');setThumbnail(null);setAssetFile(null);};
  const openEdit=(p:Product)=>{setEditing(p.id);setTitle(p.title);setCategory(p.category||CATEGORIES[0]);setDescription(p.description||'');setPrice(String(p.price));setError('');setThumbnail(null);setAssetFile(null);setModal(true);};
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(!title.trim())return setError('Product title is required.');if(!price||Number(price)<=0)return setError('Enter a valid positive price.');if(description.trim().length<10)return setError('Description must contain at least 10 characters.');if(!editing&&!assetFile)return setError('Select the digital asset file.');setSaving(true);try{const data=new FormData();data.append('title',title.trim());data.append('description',description.trim());data.append('category',category);data.append('price',price);data.append('isDigital','true');if(thumbnail)data.append('thumbnail',thumbnail);if(assetFile)data.append('assetFile',assetFile);if(editing)await apiClient.put(`/admin/products/${editing}`,data);else await apiClient.post('/admin/products',data);await load(pagination.currentPage);reset();}catch(err:any){setError(err?.response?.data?.error||'Failed to save product.');}finally{setSaving(false);}};
  const archive=async()=>{if(!deleteId)return;try{await apiClient.delete(`/admin/products/${deleteId}`);setDeleteId(null);await load(Math.min(pagination.currentPage,pagination.totalPages));}catch(err:any){setLoadError(err?.response?.data?.error||'Failed to archive product.');setDeleteId(null);}};

  return <main className={styles.container}>
    <header className={styles.header}><div><h1 className={styles.title}>Products</h1><p className={styles.sub}>Manage the digital catalog and secure assets.</p></div><button className={styles.primaryButton} onClick={()=>{reset();setModal(true)}}><Plus size={17}/> New product</button></header>
    <div className={styles.toolbar}><div style={{display:'flex',alignItems:'center',gap:8,width:'min(420px,100%)'}}><Search size={15}/><input className={styles.search} placeholder="Search products..." value={query} onChange={e=>setQuery(e.target.value)}/></div><span style={{color:'#777',fontSize:'11px'}}>{pagination.totalRecords} products</span></div>
    {loading?<div className={styles.empty}><Loader2 size={28} className="pluten-login-spinner"/><p>Loading catalog</p></div>:loadError?<div className={styles.empty}><AlertCircle size={22}/><h2>Catalog unavailable.</h2><p>{loadError}</p><button className={styles.primaryButton} onClick={()=>load(pagination.currentPage)}>Retry</button></div>:products.length===0?<div className={styles.empty}><h2>No products found.</h2><p>Create your first digital product or change the search.</p></div>:<>
      <div className={styles.tableCard}><div className={styles.tableScroll}><table className={styles.table}><thead><tr><th className={styles.th}>Product</th><th className={styles.th}>Category</th><th className={styles.th}>Price</th><th className={styles.th}>Actions</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td className={styles.td}><div className={styles.productCell}>{p.thumbnail?<img src={p.thumbnail} alt={p.title} className={styles.thumb}/>:<span className={styles.thumbFallback}>PLUTEN</span>}<strong>{p.title}</strong></div></td><td className={styles.td}>{p.category||'Uncategorized'}</td><td className={styles.td}>₹{Number(p.price).toLocaleString('en-IN')}</td><td className={styles.td}><div className={styles.actions}><button className={styles.iconButton} onClick={()=>openEdit(p)} aria-label={`Edit ${p.title}`}><Edit2 size={16}/></button><button className={`${styles.iconButton} ${styles.danger}`} onClick={()=>setDeleteId(p.id)} aria-label={`Archive ${p.title}`}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div></div>
      <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,marginTop:16,color:'#777',fontSize:11}}><span>Page {pagination.currentPage} of {pagination.totalPages}</span><div style={{display:'flex',gap:6}}><button className={styles.iconButton} disabled={pagination.currentPage<=1} onClick={()=>load(pagination.currentPage-1)}><ChevronLeft size={16}/></button><button className={styles.iconButton} disabled={pagination.currentPage>=pagination.totalPages} onClick={()=>load(pagination.currentPage+1)}><ChevronRight size={16}/></button></div></div>
    </>}
    {modal&&<div className={styles.modalOverlay} role="dialog" aria-modal="true" aria-labelledby="product-editor-title"><div className={styles.modalContent}><div className={styles.modalHeader}><div><p className={styles.sub}>PLUTEN / CATALOG</p><h2 id="product-editor-title" className={styles.modalTitle}>{editing?'Edit product':'Create product'}</h2></div><button className={styles.closeBtn} onClick={reset} aria-label="Close"><X size={18}/></button></div>{error&&<div className={styles.error}>{error}</div>}<form className={styles.form} onSubmit={submit}><div className={styles.field}><label className={styles.label}>Title</label><input className={styles.input} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Product title"/></div><div className={styles.twoCol}><div className={styles.field}><label className={styles.label}>Category</label><select className={styles.select} value={category} onChange={e=>setCategory(e.target.value)}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></div><div className={styles.field}><label className={styles.label}>Price (INR)</label><input className={styles.input} inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)} placeholder="999"/></div></div><div className={styles.field}><label className={styles.label}>Description</label><textarea className={styles.textarea} value={description} onChange={e=>setDescription(e.target.value)} placeholder="What is inside this product?"/></div><div className={styles.field}><label className={styles.label}>Cover image {editing?'(optional)':'(required)'}</label><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setThumbnail(e.target.files?.[0]||null)}/></div><div className={styles.field}><label className={styles.label}>Digital asset {editing?'(optional)':'(required)'}</label><input type="file" accept=".pdf,.zip,.docx" onChange={e=>setAssetFile(e.target.files?.[0]||null)}/></div><div className={styles.formActions}><button type="button" className={styles.secondaryButton} onClick={reset}>Cancel</button><button type="submit" className={styles.primaryButton} disabled={saving}>{saving?<><Loader2 size={16} className="pluten-login-spinner"/> Saving</>:editing?'Save changes':'Create product'}</button></div></form></div></div>}
    {deleteId&&<div className={styles.modalOverlay} role="dialog" aria-modal="true" aria-labelledby="archive-title"><div className={styles.modalContent}><p className={styles.sub}>PLUTEN / PRODUCT</p><h2 id="archive-title" className={styles.modalTitle}>Archive this product?</h2><p style={{color:'#888',fontSize:'13px',lineHeight:1.6}}>The product will disappear from the storefront, while existing buyers retain access.</p><div className={styles.formActions}><button className={styles.secondaryButton} onClick={()=>setDeleteId(null)}>Cancel</button><button className={styles.primaryButton} onClick={archive}>Archive product</button></div></div></div>}
  </main>;
}
