const prisma = require('../lib/prisma');
function getClientIp(req){const f=req.headers['x-forwarded-for'];if(typeof f==='string'&&f.trim())return f.split(',').map(v=>v.trim()).filter(Boolean)[0]||'unknown';return req.socket?.remoteAddress||'unknown';}
function detectDevice(ua=''){ua=String(ua).toLowerCase();if(/ipad|tablet|playbook|silk/i.test(ua))return 'TABLET';if(/mobile|iphone|ipod|android.+mobile|blackberry|opera mini|windows phone/i.test(ua))return 'MOBILE';if(!ua)return 'UNKNOWN';return 'DESKTOP';}
function detectBrowser(ua=''){ua=String(ua);if(/Edg\//i.test(ua))return 'Edge';if(/OPR\//i.test(ua))return 'Opera';if(/Chrome\//i.test(ua)&&!/Edg\//i.test(ua))return 'Chrome';if(/Firefox\//i.test(ua))return 'Firefox';if(/Safari\//i.test(ua)&&!/Chrome\//i.test(ua))return 'Safari';return 'Other';}
function detectOs(ua=''){ua=String(ua);if(/Windows NT/i.test(ua))return 'Windows';if(/Android/i.test(ua))return 'Android';if(/(iPhone|iPad|iPod)/i.test(ua))return 'iOS';if(/Mac OS X/i.test(ua))return 'macOS';if(/Linux/i.test(ua))return 'Linux';return 'Other';}
function getCountry(req){return String(req.headers['x-vercel-ip-country']||req.headers['cf-ipcountry']||req.headers['x-country-code']||'').trim().toUpperCase().slice(0,4)||null;}
function getContext(req){const ua=String(req.headers['user-agent']||'');return{deviceType:detectDevice(ua),browser:detectBrowser(ua),os:detectOs(ua),country:getCountry(req),ipAddress:getClientIp(req),referrer:String(req.headers.referer||req.headers.referrer||'').slice(0,1000)||null};}
async function recordAnalyticsEvent({type,visitorId,sessionKey=null,userId=null,productId=null,portfolioId=null,path=null,metadata=null,request=null,deviceType=null,browser=null,os=null,country=null,referrer=null,utmSource=null,utmMedium=null,utmCampaign=null}){
 if(!visitorId)return null;const context=request?getContext(request):{};let resolvedProductId=productId;let resolvedPortfolioId=portfolioId;
 if(!resolvedProductId&&path){const m=String(path).match(/^\/product\/([^/?#]+)/i);if(m)resolvedProductId=decodeURIComponent(m[1]).slice(0,100);}
 if(!resolvedPortfolioId&&path){const m=String(path).match(/^\/p\/([^/?#]+)/i);if(m){const username=decodeURIComponent(m[1]).trim().toLowerCase();if(username){const p=await prisma.portfolio.findFirst({where:{username,status:'PUBLISHED',visibility:'PUBLIC'},select:{id:true}}).catch(()=>null);resolvedPortfolioId=p?.id||null;}}}
 const session=sessionKey?await prisma.analyticsSession.upsert({where:{sessionKey},create:{sessionKey,visitorId,userId,currentPath:path,deviceType:deviceType||context.deviceType||'UNKNOWN',browser:browser||context.browser||null,os:os||context.os||null,country:country||context.country||null,referrer:referrer||context.referrer||null,utmSource:utmSource||null,utmMedium:utmMedium||null,utmCampaign:utmCampaign||null},update:{visitorId,userId:userId||undefined,currentPath:path||undefined,deviceType:deviceType||context.deviceType||'UNKNOWN',browser:browser||context.browser||null,os:os||context.os||null,country:country||context.country||null,referrer:referrer||undefined,utmSource:utmSource||undefined,utmMedium:utmMedium||undefined,utmCampaign:utmCampaign||undefined,lastSeen:new Date()}}):null;
 if(type==='SESSION_HEARTBEAT') return session;
 return prisma.analyticsEvent.create({data:{type,visitorId:String(visitorId).slice(0,128),sessionId:session?.id||null,userId,productId:resolvedProductId,portfolioId:resolvedPortfolioId,path:path?String(path).slice(0,1000):null,deviceType:deviceType||context.deviceType||'UNKNOWN',browser:browser||context.browser||null,os:os||context.os||null,country:country||context.country||null,metadata:metadata&&typeof metadata==='object'?metadata:undefined}});
}
module.exports={getClientIp,getContext,detectDevice,detectBrowser,detectOs,getCountry,recordAnalyticsEvent};
