"use client";
import { useEffect, useMemo, useState } from 'react';
import { AlertCircle, ChevronLeft, ChevronRight, Loader2, Users } from 'lucide-react';
import apiClient from '@/lib/apiClient';
import styles from '../admin.module.css';

type Customer={id:string;email:string;firstName:string|null;lastName:string|null;isPremium:boolean;createdAt:string;_count?:{orders:number}};
const PAGE=10;
export default function AdminCustomersPage(){
 const [rows,setRows]=useState<Customer[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(1);
 const load=async()=>{setLoading(true);setError('');try{const res=await apiClient.get('/admin/customers');setRows(Array.isArray(res.data)?res.data:[]);}catch(err:any){setError(err?.response?.data?.error||'Unable to load customers.');}finally{setLoading(false);}};useEffect(()=>{load();},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?rows.filter(c=>`${c.firstName||''} ${c.lastName||''}`.toLowerCase().includes(q)||c.email.toLowerCase().includes(q)):rows;},[rows,query]);const pages=Math.max(1,Math.ceil(filtered.length/PAGE));const visible=filtered.slice((page-1)*PAGE,page*PAGE);useEffect(()=>setPage(1),[query]);
 return <main className={styles.dashboardContainer}><div className={styles.header}><div><p className={styles.pageEyebrow}>PLUTEN / CUSTOMERS</p><h1 className={styles.pageTitle}>Customers</h1></div><div className={styles.topbarRole}><Users size={13}/> {filtered.length}</div></div><div className={styles.pageToolbar}><input className={styles.toolbarSearch} placeholder="Search name or email..." value={query} onChange={e=>setQuery(e.target.value)}/></div>{loading?<div className={styles.authLoading}><Loader2 size={28} className="pluten-login-spinner"/><span>Loading customers</span></div>:error?<div className={styles.errorState}><AlertCircle size={22}/><h2>Customer directory unavailable.</h2><p>{error}</p><button className={styles.primaryButton} onClick={load}>Retry</button></div>:filtered.length===0?<div className={styles.emptyState}><Users size={24}/><h2>No customers found.</h2><p>Try a different search.</p></div>:<><div className={styles.tableCard}><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th className={styles.th}>Customer</th><th className={styles.th}>Email</th><th className={styles.th}>Purchases</th><th className={styles.th}>Status</th><th className={styles.th}>Joined</th></tr></thead><tbody>{visible.map(c=><tr key={c.id}><td className={styles.td}><strong>{`${c.firstName||''} ${c.lastName||''}`.trim()||'Unnamed customer'}</strong></td><td className={styles.td}>{c.email}</td><td className={styles.td}>{c._count?.orders||0}</td><td className={styles.td}>{c.isPremium?'Premium':'Standard'}</td><td className={styles.td}>{new Date(c.createdAt).toLocaleDateString('en-IN')}</td></tr>)}</tbody></table></div></div><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,marginTop:16,color:'#777',fontSize:11}}><span>Page {page} of {pages}</span><div style={{display:'flex',gap:6}}><button className={styles.iconBtn} disabled={page===1} onClick={()=>setPage(v=>Math.max(1,v-1))}><ChevronLeft size={16}/></button><button className={styles.iconBtn} disabled={page===pages} onClick={()=>setPage(v=>Math.min(pages,v+1))}><ChevronRight size={16}/></button></div></div></>}</main>;
}
