'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, BarChart3, ChevronRight, Crown, Database, Eye, Loader2, RefreshCw, ShoppingCart, Smartphone, Users, WalletCards } from 'lucide-react';
import apiClient from '@/lib/apiClient';
import styles from './admin.module.css';

type Range = 'today' | '7d' | '30d' | '90d';
type Overview = { range: string; metrics: any; revenueSeries: any[]; topProducts: any[]; devices: any[]; sources: any[]; countries: any[]; funnel: any; recentOrders: any[]; attention: any[] };
type Live = { count: number; sessions: any[] };
const money = (v: number) => `₹${Number(v || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;
const pct = (v: number) => `${Number(v || 0).toFixed(v % 1 ? 1 : 0)}%`;
export default function AdminDashboard() {
    const [range, setRange] = useState<Range>('30d'); const [data, setData] = useState<Overview | null>(null); const [live, setLive] = useState<Live>({ count: 0, sessions: [] }); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
    const load = useCallback(async () => { try { const [a, b] = await Promise.all([apiClient.get('/admin/overview', { params: { range } }), apiClient.get('/admin/live')]); setData(a.data); setLive(b.data); setError(''); } catch (e: any) { setError(e?.response?.data?.error || 'Unable to load founder telemetry.'); } finally { setLoading(false); } }, [range]);
    useEffect(() => { load(); const t = window.setInterval(load, 20000); return () => window.clearInterval(t); }, [load]);
    const maxRevenue = Math.max(1, ...(data?.revenueSeries || []).map(x => Number(x.revenue || 0)));
    const funnelMax = Math.max(1, Number(data?.funnel?.visitors || 0));
    const deviceTotal = Math.max(1, (data?.devices || []).reduce((a, x) => a + Number(x.value || 0), 0));
    const sourceTotal = Math.max(1, (data?.sources || []).reduce((a, x) => a + Number(x.value || 0), 0));
    const rangeLabel = useMemo(() => range === 'today' ? 'Today' : range === '7d' ? 'Last 7 days' : range === '90d' ? 'Last 90 days' : 'Last 30 days', [range]);
    if (loading && !data) return <div className={styles.authLoading}><Loader2 className={styles.spin} size={28} /><span>Loading Pluten command center</span></div>;
    return <main className={styles.dashboardContainer}>
        <div className={styles.header}><div><p className={styles.pageEyebrow}>PLUTEN / FOUNDER COMMAND CENTER</p><h1 className={styles.pageTitle}>Overview.</h1></div><div className={styles.rangeBar}>{(['today', '7d', '30d', '90d'] as Range[]).map(r => <button key={r} className={`${styles.rangeBtn} ${range === r ? styles.rangeBtnActive : ''}`} onClick={() => setRange(r)}>{r === 'today' ? 'Today' : r.toUpperCase()}</button>)}</div></div>
        {error ? <div className={styles.errorState}><AlertTriangle size={22} /><h2>Telemetry unavailable.</h2><p>{error}</p><button className={styles.primaryButton} onClick={load}><RefreshCw size={14} /> Retry</button></div> : <>
            <div className={styles.metricGrid}>
                <div className={styles.metricCard}><span className={styles.metricLabel}>Today's revenue</span><strong className={styles.metricValue}>{money(data?.metrics?.todayRevenue)}</strong><span className={styles.metricTrendUp}>{data?.metrics?.todayOrders || 0} successful orders today</span></div>
                <div className={styles.metricCard}><span className={styles.metricLabel}>Period revenue</span><strong className={styles.metricValue}>{money(data?.metrics?.revenue)}</strong><span className={styles.metricTrendUp}>↗ {pct(data?.metrics?.revenueDelta)} vs previous</span></div>
                <div className={styles.metricCard}><span className={styles.metricLabel}>Unique visitors</span><strong className={styles.metricValue}>{data?.metrics?.uniqueVisitors || 0}</strong><span className={styles.metricTrendUp}>{data?.metrics?.returningVisitors || 0} returning</span></div>
                <div className={styles.metricCard}><span className={styles.metricLabel}>Product views</span><strong className={styles.metricValue}>{data?.metrics?.productViews || 0}</strong><span className={styles.metricTrendUp}>{pct(data?.metrics?.viewToPurchase)} view → sale</span></div>
                <div className={styles.metricCard}><span className={styles.metricLabel}>Live now</span><strong className={styles.metricValue}>{live.count}</strong><span className={styles.metricTrendUp}><span className={styles.liveDot} />active sessions</span></div>
            </div>
            <div className={styles.grid2}>
                <section className={styles.panel}><div className={styles.panelHead}><div><div className={styles.panelTitle}>Revenue</div><div className={styles.panelSub}>{rangeLabel}</div></div><WalletCards size={16} /></div><div className={styles.panelBody}><div className={styles.chart}>{(data?.revenueSeries || []).map((r, i) => <div className={styles.barWrap} key={r.day || i}><div title={`${r.day}: ${money(r.revenue)}`} className={styles.bar} style={{ height: `${Math.max(2, (Number(r.revenue || 0) / maxRevenue) * 100)}%` }} /><span className={styles.barLabel}>{String(r.day || '').slice(5)}</span></div>)}</div></div></section>
                <section className={styles.panel}><div className={styles.panelHead}><div><div className={styles.panelTitle}>Conversion funnel</div><div className={styles.panelSub}>Where visitors disappear</div></div><ChevronRight size={16} /></div><div className={styles.panelBody}><div className={styles.funnel}>{[['Visitors', data?.funnel?.visitors], ['Product viewers', data?.funnel?.productViewers], ['Checkout starts', data?.funnel?.checkouts], ['Payment attempts', data?.funnel?.paymentAttempts], ['Purchases', data?.funnel?.purchases]].map(([label, val]: any) => <div className={styles.funnelRow} key={label}><span>{label}</span><div className={styles.funnelBarBg}><div className={styles.funnelBar} style={{ width: `${Math.min(100, (Number(val || 0) / funnelMax) * 100)}%` }} /></div><span className={styles.funnelValue}>{Number(val || 0)}</span></div>)}</div></div></section>
            </div>
            <div className={styles.grid3}>
                <section className={styles.panel}><div className={styles.panelHead}><div><div className={styles.panelTitle}>Best selling products</div><div className={styles.panelSub}>Orders + revenue</div></div><BarChart3 size={16} /></div><div className={styles.panelBody}><div className={styles.list}>{(data?.topProducts || []).slice(0, 6).map((p: any, i: number) => <div className={styles.listRow} key={p.id}><div><div className={styles.listMain}>{i + 1}. {p.title}</div><div className={styles.listMeta}>{p.orders} orders</div></div><div className={styles.listValue}>{money(p.revenue)}</div></div>)}</div></div></section>
                <section className={styles.panel}><div className={styles.panelHead}><div><div className={styles.panelTitle}>Devices</div><div className={styles.panelSub}>Traffic split</div></div><Smartphone size={16} /></div><div className={styles.panelBody}>{(data?.devices || []).map((d: any) => <div className={styles.split} key={d.device}><span>{d.device}</span><strong>{pct((Number(d.value || 0) / deviceTotal) * 100)}</strong></div>)}</div></section>
                <section className={styles.panel}><div className={styles.panelHead}><div><div className={styles.panelTitle}>Traffic sources</div><div className={styles.panelSub}>Sessions by source</div></div><Eye size={16} /></div><div className={styles.panelBody}>{(data?.sources || []).slice(0, 6).map((s: any) => <div className={styles.split} key={s.source}><span>{s.source}</span><strong>{pct((Number(s.value || 0) / sourceTotal) * 100)}</strong></div>)}</div></section>
            </div>
            <div className={styles.grid2}>
                <section className={styles.panel}><div className={styles.panelHead}><div><div className={styles.panelTitle}><span className={styles.liveDot} />{live.count} live visitors</div><div className={styles.panelSub}>Updated every 20 seconds</div></div><Activity size={16} /></div><div className={styles.panelBody}><div className={styles.tableScroll}><table className={styles.liveTable}><thead><tr><th>Page</th><th>Device</th><th>Country</th><th>Visitor</th><th>Last seen</th></tr></thead><tbody>{(live.sessions || []).slice(0, 10).map((s: any) => <tr key={s.sessionKey}><td className={styles.mono}>{s.currentPath || '/'}</td><td>{s.deviceType}</td><td>{s.country || '—'}</td><td>{s.user?.email || String(s.visitorId).slice(0, 12)}</td><td>{new Date(s.lastSeen).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })}</td></tr>)}</tbody></table></div></div></section>
                <section className={styles.panel}><div className={styles.panelHead}><div><div className={styles.panelTitle}>Attention required</div><div className={styles.panelSub}>Issues worth checking now</div></div><AlertTriangle size={16} /></div><div className={styles.panelBody}>{(data?.attention || []).length ? <div className={styles.attention}>{data?.attention?.map((a: any, i: number) => <div className={styles.attentionItem} key={i}><div className={styles.attentionTitle}>{a.title}</div><div className={styles.attentionDetail}>{a.detail}</div></div>)}</div> : <div className={styles.emptyState}><Database size={18} /><p>Nothing urgent right now.</p></div>}</div></section>
            </div>
            <div className={styles.grid3}>
                <section className={styles.panel}><div className={styles.panelHead}><div><div className={styles.panelTitle}>Portfolio activity</div><div className={styles.panelSub}>Created / published in selected period</div></div><Users size={16} /></div><div className={styles.panelBody}><div className={styles.split}><span>Created</span><strong>{data?.metrics?.portfolioCreated || 0}</strong></div><div className={styles.split}><span>Published</span><strong>{data?.metrics?.portfolioPublished || 0}</strong></div><div className={styles.split}><span>Users</span><strong>{data?.metrics?.totalUsers || 0}</strong></div></div></section>
                <section className={styles.panel}><div className={styles.panelHead}><div><div className={styles.panelTitle}>Customer depth</div><div className={styles.panelSub}>Relationship, not just signup count</div></div><Crown size={16} /></div><div className={styles.panelBody}><div className={styles.split}><span>New customers</span><strong>{data?.metrics?.newCustomers || 0}</strong></div><div className={styles.split}><span>Repeat customers</span><strong>{data?.metrics?.repeatCustomers || 0}</strong></div><div className={styles.split}><span>Returning visitor rate</span><strong>{pct(data?.metrics?.returningRate)}</strong></div></div></section>
                <section className={styles.panel}><div className={styles.panelHead}><div><div className={styles.panelTitle}>Payment health</div><div className={styles.panelSub}>Operational state</div></div><ShoppingCart size={16} /></div><div className={styles.panelBody}><div className={styles.split}><span>Pending orders</span><strong>{data?.metrics?.pendingOrders || 0}</strong></div><div className={styles.split}><span>Failed payments</span><strong>{data?.metrics?.failedPayments || 0}</strong></div><div className={styles.split}><span>Average order value</span><strong>{money(data?.metrics?.averageOrderValue)}</strong></div></div></section>
            </div>
        </>}
    </main>;
}
